# this is to prepare local development environment
version: "3.8"
#name: "devaegis_backend_service"

services:
  devaegis_backend:
    container_name: devaegis_backend
    image: devaegis_backend:local
#    networks:
#      - scantist-network
    build:
      context: .
      dockerfile: compose/local/devaegis/Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: /entrypoint.sh
    privileged: true
    ports:
      - "8000:8000"
    environment:
        FLASK_APP: autoapp.py
    env_file:
      - .env

#networks:
#  scantist-network:
#    name: scantist-network
